# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Test with unittest
      run: |
        coverage run -m tictactoe_unit_test discover
        coverage report
        
  docker-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker image
        run: docker build -t tictactoe .
        
        
  push_to_registry:
    name: Deploy Docker image to the Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: Docker repo
        uses: actions/checkout@v2
      - name: Deploy to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: mplh2008
          password: Caroline192!
          repository: mplh2008/tic_tactoe
          
          tag_with_ref: true
