# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Test with unittest
      run: |
        coverage run -m tictactoe_unit_test
        coverage report
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: mplh2008/tic_tactoe@master
      with:
        script: .github/testScript.sh
  docker-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker image
        run: docker build -t tictactoe .
        
        
  push_to_registry:
    name: Deploy Docker image to the Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: Docker repo
        uses: actions/checkout@v2
      - name: Deploy to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: mplh2008
          password: Caroline192!
          repository: mplh2008/tic_tactoe:tagname
          
          tag_with_ref: true
